data_root: ../data
img_size: 512
val_ratio: 0.2
num_workers: 2
cache_rate: 1.0
epochs: 200
batch_size: 4
loss: dice+bce@0.8,0.2
lr: 0.0001
optimizer: adamw
use_green_channel: true
use_patch: true
seed: 42
base_channels: 64
depth: 3
in_channels: 3
out_channels: 1
device: cuda
early_stopping: true
patience: 20
activation: leaky_relu
up_mode: bilinear
save_dir: checkpoints
save_plots_path: results/predictions